---
# Configuration
server: "10.11.0.1"
port: "3100"
cidr: "16"
dns: "1.1.1.1"
configPath: "/etc/wireguard/wg0.conf"

clients:
  - 10.11.0.0/24: "servers"
    - 10.11.0.1/32: "DNS"
  - 10.11.1.0/24: "clients"
    - 10.11.1.3/32: "macbook"
